### PR TITLE
Update logback to 1.4.11

### PR DESCRIPTION
**Pull request by marbon87**
As a preparation for some future pull-requests regarding new featues in slf4j 2.0 this pull-requests updates the dependencies to the latest version and updates the required java version to 11.

### CODE REVIEW

**Comment by osiegmar** [comment]
Please target the develop branch.

**Comment by osiegmar** [comment]
Merge conflict. Updated by https://github.com/osiegmar/logback-gelf/commit/d143b470c0a5f592d984ec65cb2b27d7e4fb36ea

**Comment by marbon87** [comment]
Hi @osiegmar,
could you release the current version in the near future?

**Comment by osiegmar** [comment]
Yes, this is planned for this month.

**Pull request closed without merging**
