### PR TITLE
Add newline to JSON

### PR DESCRIPTION
**Pull request by xolve**

### CODE REVIEW

**Comment by osiegmar** [comment]
Why?

**Comment by xolve** [comment]
I am using a STDOUT -> Heka -> Kafka -> Graylog -> Elasticsearch pipeline. Here each log message is read from a line it STDOUT and sent to graylog.

I use this logback.xml to print each message as GELF JSON: https://gist.github.com/xolve/968e5eff62571f93abdec501fcb911d3

So need to add a new line. Would probably add an option to enable disable this.

**Comment by osiegmar** [comment]
Thanks for your input! I've added support for console logging via extending GelfLayout - see https://github.com/osiegmar/logback-gelf/commit/12faee0701ffd3a4b45cd2192e88449111f733db

**Comment by xolve** [comment]
Could you release a minor version to maven central?

**Comment by xolve** [comment]
Grateful for a the feature :) Can you please release the build to maven central.

**Comment by osiegmar** [comment]
done

**Comment by xolve** [comment]
Thanks a lot :)

**Comment by xolve** [comment]
Thanks a lot :)

**Pull request closed without merging**
