### PR TITLE
Make the field name for levelName configurable

### PR DESCRIPTION
**Pull request by BastianVoigt**
For a project I need to use "Severity" as the field name for the loglevel, so I made this configurable.

### CODE REVIEW

**Comment by BastianVoigt** [comment]
Hmm, apparently it fails because of checkstyle, but I cannot see what the problem is:

> Checkstyle rule violations were found. See the report at: file:///home/travis/build/osiegmar/logback-gelf/build/reports/checkstyle/main.html
  Checkstyle files with violations: 1
  Checkstyle violations by severity: [error:2]

**Comment by osiegmar** [comment]
Look a few lines above:

```
> Task :checkstyleMain
[ant:checkstyle] [ERROR] /home/travis/build/osiegmar/logback-gelf/src/main/java/de/siegmar/logbackgelf/GelfEncoder.java:88: First sentence should end with a period. [JavadocStyle]
[ant:checkstyle] [ERROR] /home/travis/build/osiegmar/logback-gelf/src/main/java/de/siegmar/logbackgelf/GelfEncoder.java:176:33: Parameter levelNameKey should be final. [FinalParameters]
```

**Comment by BastianVoigt** [comment]
@osiegmar Thanks for your help! Sometimes it helps when you are able to read. ;)

**Comment by BastianVoigt** [comment]
@osiegmar Do you see a chance of integrating this and building a new release in the near future?

**Comment by osiegmar** [comment]
Will build a new release soon ;-)

**Pull request merged**
